### ISSUE TITLE
it doesnot work with streamable file playlist.m3u8

### ISSUE THREAD

**Issue by Chomroeun** [BunnyWay/BunnyCDN.TokenAuthentication#5]
video can be use with other resolution such as play_720p.mp4 ... but it does not work with playlist.m3u8
here is my code

var queryString = require("querystring");
var crypto = require("crypto");

function addCountries(url, a, b) {
	var tempUrl = url;
	if (a != null) {
		var tempUrlOne = new URL(tempUrl);
		tempUrl += ((tempUrlOne.search == "") ? "?" : "&") + "token_countries=" + a;
	}
	if (b != null) {
		var tempUrlTwo = new URL(tempUrl);
		tempUrl += ((tempUrlTwo.search == "") ? "?" : "&") + "token_countries_blocked=" + b;
	}
	return tempUrl;
}

function signUrl(url, securityKey, expirationTime = 3600, userIp, isDirectory = false, pathAllowed, countriesAllowed, countriesBlocked) {
	/*
		url: CDN URL w/o the trailing '/' - exp. http://test.b-cdn.net/file.png
		securityKey: Security token found in your pull zone
		expirationTime: Authentication validity (default. 86400 sec/24 hrs)
		userIp: Optional parameter if you have the User IP feature enabled
		isDirectory: Optional parameter - "true" returns a URL separated by forward slashes (exp. (domain)/bcdn_token=...)
		pathAllowed: Directory to authenticate (exp. /path/to/images)
		countriesAllowed: List of countries allowed (exp. CA, US, TH)
		countriesBlocked: List of countries blocked (exp. CA, US, TH)
	*/
	var parameterData = "", parameterDataUrl = "", signaturePath = "", hashableBase = "", token = "";
	var expires = Math.floor(new Date() / 1000) + expirationTime;
	var url = addCountries(url, countriesAllowed, countriesBlocked);
	var parsedUrl = new URL(url);
	var parameters = (new URL(url)).searchParams;
	if (pathAllowed != null) {
		signaturePath = pathAllowed;
		parameters.set("token_path", signaturePath);
	} else {
		signaturePath = decodeURIComponent(parsedUrl.pathname);
	}
	parameters.sort()
	if (Array.from(parameters).length > 0) {
		parameters.forEach(function(value, key) {
		  if (parameterData.length > 0) {
		  	parameterData += "&";
		  }
		  parameterData += key + "=" + value;
		  parameterDataUrl += "&" + key + "=" + queryString.escape(value);

		});
	}
	hashableBase = securityKey + signaturePath + expires + ((userIp != null) ? userIp : "") + parameterData;
	token = Buffer.from(crypto.createHash("sha256").update(hashableBase).digest()).toString("base64");
	token = token.replace(/\n/g, "").replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
	if (isDirectory) {
		return parsedUrl.protocol+ "//" + parsedUrl.host + "/bcdn_token=" + token + parameterDataUrl + "&expires=" + expires + parsedUrl.pathname;
	} else {
		return parsedUrl.protocol + "//" + parsedUrl.host + parsedUrl.pathname + "?token=" + token + parameterDataUrl + "&expires=" + expires;
	}
}

var securityKey = "my-security-token";
var signedUrl = signUrl("https://vz-44c78a82-e6f.b-cdn.net/4635c38f-7cc0-460a-960e-ae4e3f280c09/playlist.m3u8", securityKey, 7200);
console.log(signedUrl);
 this result does not work: https://vz-44c78a82-e6f.b-cdn.net/4635c38f-7cc0-460a-960e-ae4e3f280c09/playlist.m3u8?token=CCLiDQyvyFKHWu_FeWqNmMB6FWY2ijAWJwJME-yGf5Y&expires=1628544150

but if I use 
var securityKey = "my-security-token";
var signedUrl = signUrl("https://vz-44c78a82-e6f.b-cdn.net/4635c38f-7cc0-460a-960e-ae4e3f280c09/play_720p.mp4", securityKey, 7200);

this result it works fine : https://vz-44c78a82-e6f.b-cdn.net/4635c38f-7cc0-460a-960e-ae4e3f280c09/play_720p.mp4?token=BD70mCbmYvOLxg0YLEpbQet4-aPu2--jCq6MNoEO-RA&expires=1628544070

**Comment by Chomroeun** [comment]
I have tried open ticket but no solution for me. 
the MP4 file download fine but for playlist file (.m3u8) does not work, it can be download file .m3u8 but it does not the video

**Comment by Chomroeun** [comment]
I want to know the format of URL (https://vz-44c78a82-e6f.b-cdn.net/4635c38f-7cc0-460a-960e-ae4e3f280c09/playlist.m3u8) it is correct right ? or I had provide wrong format ????

**Comment by Chomroeun** [comment]
> Oddly enough -- using your links -- the playlist file and MP4 downloaded fine?
> 
> ![console](https://camo.githubusercontent.com/1c8425bc915800a195d01505922dc930801a1c38405c032d128e099d66b3652c/68747470733a2f2f632e307a2e706d2f323032312f4175677573742f53637265656e2d53686f742d323032312d30382d30392d61742d30352d30322d33362d504d2d584b6d505a302e706e67)
> 
> I'd advise you to open a ticket as it might be a configuration issue; I am not able to reproduce the issue on my end.

you can steam now because I disable CDN token restriction.

**Comment by doghouch** [comment]
Just to make sure: I pushed an update out today to fix a bug in the NodeJS implementation of the token signer — could you try `git pull`’ing the repository to get the latest files? 

---

That said, the format looks fine. I’ll take a look into the issue in the morning as it is rather late where I am — sorry about that!

**Comment by Chomroeun** [comment]
it still does not work

https://vz-693666e8-25d.b-cdn.net/9a240ac8-9715-49ea-a49a-c6774d33d936/playlist.m3u8?token=2brirYYveOJDtQ354BGnHz6NrDO0GE3I38Loqi_qISc&token_countries=KH%2CUS&token_countries_blocked=JP&token_path=%2F&expires=1628612543

**Comment by doghouch** [comment]
One final question: do you have this setting turned on?

![](https://c.0z.pm/2021/August/Screen-Shot-2021-08-10-at-04-23-58-PM-NSO2Xl.png)

--- 

On my own zone, I had to turn the option off before using token authentication (otherwise it would 403 as well). Using the following on a test zone:

```
var securityKey = "token-here";
var signedUrl = signUrl("https://vz-d99a160d-b45.b-cdn.net/3a57ead3-e714-47da-94fb-cfcf234d780e/playlist.m3u8", securityKey, 172800, "", false, "", "CA,KH,US", "CN");
```

yielded https://vz-d99a160d-b45.b-cdn.net/3a57ead3-e714-47da-94fb-cfcf234d780e/playlist.m3u8?token=f5LnSodqyJA8Tg3MZ2USCkMi5A_1dk8DBnikCDIG55o&token_countries=CA%2CKH%2CUS&token_countries_blocked=CN&expires=1628800432 (a valid token-authenticated URL).

**Comment by doghouch** [comment]
@Chomroeun 

Just a followup - did you manage to get it to work?

**Comment by doghouch** [comment]
I'm closing this due to inactivity - if you get a chance, re-open the issue by replying below.

**Comment by LErox17** [comment]
Can you explain this process in coding illiterate terms please?  I need to download this video:

https://vz-6db32718-53a.b-cdn.net/edb4d4c9-d9da-4bf9-8ed2-d490b89a5665/playlist.m3u8
